--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BOFOII/ultimate-parkour
build-by-default: true
branches:
- main
projects:
  ultimate-parkour:
    path: ""
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1

...
