---
name: UtimateParkour
version: 0.0.1
main: bofoiii\parkour\Parkour
api: 5.3.0
author: BOFOII
permissions:
  ultimateparkour.command:
    default: true
  ultimateparkour.command.set:
    default: op
...
